// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package mysql

import (
	"database/sql"
)

type EscapeOrder struct {
	ID              string       `json:"id"`
	OrderSource     int32        `json:"order_source"`
	LoyaltyMemberID string       `json:"loyalty_member_id"`
	OrderStatus     int32        `json:"order_status"`
	Updated         sql.NullTime `json:"updated"`
}
