// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgresql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type OrdersOrder struct {
	ID              uuid.UUID      `json:"id"`
	UserID          int64          `json:"user_id"`
	OrderNumber     string         `json:"order_number"`
	Status          string         `json:"status"`
	TotalPrice      int64          `json:"total_price"`
	Quantity        int32          `json:"quantity"`
	PaymentMethod   string         `json:"payment_method"`
	ShippingFee     int32          `json:"shipping_fee"`
	ShippingAddress string         `json:"shipping_address"`
	OrderedAt       time.Time      `json:"ordered_at"`
	PaidAt          sql.NullTime   `json:"paid_at"`
	Memo            sql.NullString `json:"memo"`
}

type OrdersOrderItem struct {
	ID             uuid.UUID             `json:"id"`
	OrderID        uuid.UUID             `json:"order_id"`
	ProductID      uuid.UUID             `json:"product_id"`
	ProductName    string                `json:"product_name"`
	ProductPrice   int64                 `json:"product_price"`
	ProductOptions pqtype.NullRawMessage `json:"product_options"`
	Quantity       int32                 `json:"quantity"`
}
